### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by vivalazy** [tatsuokun/context2vec#3]
Loading input file
Creating dataset
100 5 300 600 cpu
Context2vec(
  (drop): Dropout(p=0.0)
  (l2r_emb): Embedding(6075, 300, padding_idx=1)
  (l2r_rnn): LSTM(300, 600, batch_first=True)
  (r2l_emb): Embedding(6075, 300, padding_idx=1)
  (r2l_rnn): LSTM(300, 600, batch_first=True)
  (criterion): NegativeSampling(
    (W): Embedding(6075, 600, padding_idx=1)
    (logsigmoid): LogSigmoid()
  )
  (MLP): MLP(
    (drop): Dropout(p=0.0)
    (MLP): ModuleList(
      (0): Linear(in_features=1200, out_features=1200, bias=True)
      (1): Linear(in_features=1200, out_features=600, bias=True)
    )
    (activation_function): ReLU()
  )
)
Traceback (most recent call last):
  File "/anaconda3/envs/context2vec/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/context2vec/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yingzhang/Documents/git/context2vec/src/__main__.py", line 5, in <module>
    sys.exit(main())
  File "/Users/yingzhang/Documents/git/context2vec/src/main.py", line 125, in main
    for batch in iterator:
  File "/anaconda3/envs/context2vec/lib/python3.6/site-packages/torchtext/data/iterator.py", line 156, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/anaconda3/envs/context2vec/lib/python3.6/site-packages/torchtext/data/batch.py", line 34, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "/anaconda3/envs/context2vec/lib/python3.6/site-packages/torchtext/data/field.py", line 237, in process
    tensor = self.numericalize(padded, device=device)
  File "/anaconda3/envs/context2vec/lib/python3.6/site-packages/torchtext/data/field.py", line 336, in numericalize
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
  File "/anaconda3/envs/context2vec/lib/python3.6/site-packages/torchtext/data/field.py", line 336, in <listcomp>
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
  File "/anaconda3/envs/context2vec/lib/python3.6/site-packages/torchtext/data/field.py", line 336, in <listcomp>
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
KeyError: 'lucky'

**Comment by tatsuokun** [comment]
Hi,
My scripts assume that all the unknown words are converted to a special unk token such as '<UNK>' in advance.
But you can write exception about this or just run preprocessing that replace unk token with unk symbol.

**Comment by vivalazy** [comment]
I just run "python -m src --train", and the dataset is sample.txt

**Comment by vivalazy** [comment]
I didn't modify anything, just want to run your sample. 
And the key error word is different everytime.
